stages:
  split:
    cmd: python src/data/split_data.py
    deps:
      - src/data/split_data.py
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  normalize:
    cmd: python src/data/normalize_data.py
    deps:
      - src/data/normalize_data.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
    outs:
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv
      - models/scaler.pkl

  gridsearch:
    cmd: python src/models/gridsearch.py
    deps:
      - src/models/gridsearch.py
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
    outs:
      - models/best_params.pkl

  train:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - models/best_params.pkl
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
    outs:
      - models/final_model.pkl

  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
      - src/models/evaluate_model.py
      - models/final_model.pkl
      - data/processed/X_test_scaled.csv
      - data/processed/y_test.csv
    outs:
      - data/processed/predictions.csv
      - metrics/scores.json
